# Generated by Django 5.1.6 on 2025-02-20 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wordpress_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('nome', models.EmailField(max_length=254, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenca_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('cancelada', 'Cancelada')], max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField()),
                ('jwt_token', models.CharField(max_length=255)),
                ('tipo_licenca', models.CharField(choices=[('diaria', 'Diária'), ('mensal', 'Mensal'), ('anual', 'Anual')], default='mensal', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.cliente')),
            ],
        ),
    ]
