# Generated by Django 5.1.6 on 2025-02-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0002_cliente_email_alter_cliente_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='wordpress_id',
            new_name='asaas_id',
        ),
    ]
