# Generated by Django 5.1.6 on 2025-02-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0004_cliente_cpf_cnpj_cliente_inscricao_estadual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='asaas_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
