# Generated by Django 5.1.6 on 2025-02-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0005_alter_cliente_asaas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenca',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
