# Generated by Django 5.1.6 on 2025-02-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0006_alter_licenca_data_expiracao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='telefone',
            new_name='telefone_1',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telefone_celular',
            new_name='telefone_2',
        ),
        migrations.AlterField(
            model_name='licenca',
            name='tipo_licenca',
            field=models.CharField(choices=[('diaria', 'Diária'), ('mensal', 'Mensal'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=10),
        ),
    ]
