# Generated by Django 5.1.7 on 2025-03-06 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0007_rename_telefone_cliente_telefone_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_pessoa', models.CharField(choices=[('FISICA', 'Pessoa Física'), ('JURIDICA', 'Pessoa Jurídica')], default='JURIDICA', max_length=10)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone_1', models.CharField(blank=True, max_length=21, null=True)),
                ('telefone_2', models.CharField(blank=True, max_length=21, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('agencia', models.CharField(blank=True, max_length=50, null=True)),
                ('conta_corrente', models.CharField(blank=True, max_length=50, null=True)),
                ('pix_chave', models.CharField(blank=True, max_length=255, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('prazo_pagamento', models.IntegerField(default=30)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desconto_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_ult_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('FISICA', 'Pessoa Física'), ('JURIDICA', 'Pessoa Jurídica')], default='FISICA', max_length=10),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='licencas.cliente'),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licencas.cliente'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='licencas.fornecedor'),
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('grupo', models.CharField(choices=[('digital', 'Digital'), ('fisico', 'Físico')], default='digital', max_length=7)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variacoes', models.CharField(blank=True, max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licencas.fornecedor')),
            ],
        ),
    ]
